version: 2
project_name: mapotf

before:
  hooks:
    - go mod tidy

builds:
  - id: mapotf
    main: ./
    binary: mapotf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/Azure/mapotf/cmd.version={{.Version}}
      - -X github.com/Azure/mapotf/cmd.commit={{.Commit}}
      - -X github.com/Azure/mapotf/cmd.date={{.Date}}

archives:
  - id: mapotf
    ids:
      - mapotf
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  draft: false
  prerelease: auto
