name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b #v5.4.0
        with:
          go-version-file: go.mod
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #v3.1.2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@45775bd8235c68ba998cffa5171334d58593da47 #v3.28.15
        with:
          languages: go
      - name: Run build
        run: |
          go build github.com/Azure/mapotf
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@45775bd8235c68ba998cffa5171334d58593da47 #v3.28.15
      - name: Run tests

        run: go test -v github.com/Azure/mapotf/...
      - name: golangci-lint
        if: runner.os == 'Linux'
        run: |
          docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v2.1.2-alpine golangci-lint run -v --timeout=3600s
      - name: Run Gosec Security Scanner
        uses: securego/gosec@955a68d0d19f4afb7503068f95059f7d0c529017 #v2.22.3
        if: runner.os == 'Linux'